In [3]:
# 3 NumPy Arrays

In [2]:
import numpy as np

In [5]:
#3.1 1D NumPy Arrays
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)
arr *= 4
print(arr)
mean = np.mean(arr)
print(mean)
median = np.median(arr)
standard_deviation = np.std(arr)
print(standard_deviation)
smallest_index = np.argmin(arr)
largest_index = np.argmax(arr)
print(smallest_index)
print(largest_index)
min_val = np.min(arr)
max_val = np.max(arr)
valid_values = arr > 20
new_array = arr[valid_values]
print(new_array)

[ 80 108  36  48 124  68  16 200 156 140]
97.6
55.31582052180009
6
7
[ 80 108  36  48 124  68 200 156 140]


In [6]:
#3.2 2D NumPy Arrays
matrix = np.array([
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
])
print(np.shape(matrix))
print(matrix[:, 2])
print(matrix[1, :])
matrix *= 2
print(matrix)
mean = np.mean(matrix)
print(mean)
print(np.max(matrix, axis = 1))
print(np.min(matrix, axis = 0))
matrix = matrix.flatten()
print(matrix)
# The flatten function took all the values of the matrix and reshaped them into a single
# dimension
small_index = np.argmin(matrix)
print(small_index)
large_index = np.argmax(matrix)
print(large_index)
print(np.unravel_index(large_index, small_index))
valid_index = matrix > 15
valid_matrix = matrix[valid_index]
print(valid_matrix)
sorted_version = np.sort(valid_matrix, axis = 0)
print(sorted_version)

(3, 4)
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
23.0
[34 42 38]
[10 24 28  6]
[10 24 34 18 16 42 28  6 12 26 38 22]
7
5
(np.int64(5),)
[24 34 18 16 42 28 26 38 22]
[16 18 22 24 26 28 34 38 42]


In [7]:
# 4 Prime Star Systems
arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])

def prime_tester(n):
    if n > 1:
        for i in range(2, int(np.ceil((n**0.5 + 1)))):
            if n % i == 0:
                return False 
            else:
                return True
    else: return False
for j in arr:
    for k in j:
        if prime_tester(k) == True:
            x = True
        else:
            x = False
    if x == True:
        print(j)


[2 3 5]
[11 13 17]
[ 7 10 13]


In [8]:
#5 Let's Play Checkers!

In [9]:
#5.1
checkers = np.zeros((8,8))
print(checkers)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [10]:
#5.2
checkers[0:8:2, 0:8:2] = 1
print(checkers)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
#5.3
checkers[1:8:2, 1:8:2] = 1
print(checkers)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [12]:
#5.4
def reverse_checkerboard():
    checkers = np.zeros((8,8))
    checkers[0:8:2, 1:8:2] = 1
    checkers[1:8:2, 0:8:2] = 1
    return checkers
reverse_checkerboard()
print(checkers)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [4]:
# 6 The Expanding Universe
def expansion(array, spaces):
    result = []
    for word in array:
        word_list = list(word)
        result.append((" " * spaces).join(word_list))
    return result
    
universe = np.array(["galaxy", "clusters"])
print(expansion(universe, 3))



['g   a   l   a   x   y', 'c   l   u   s   t   e   r   s']


In [8]:
# 7 Second-Brightest Star
np.random.seed(1868)
stars = np.random.randint(500, 2000, (5, 5))
print(stars)

def secondBrightest(arr):
    for i in arr:
        return np.partition(arr, -2, axis = 1)[:, -2]

print(secondBrightest(stars))

[[1108 1376 1550 1260  804]
 [ 734 1017 1796 1905 1153]
 [1262 1211  793 1308 1799]
 [1466 1893 1903 1937  661]
 [1324 1590 1425  597  905]]
[1376 1796 1308 1903 1425]
